trigger:
  - master
jobs:
  - job: run_custom_task
    pool:   
      vmImage: ubuntu-latest
    variables:
      buildConfiguration: Build
    steps:
      - powershell: |
          $env:X = Get-Content -Path "$(Build.SourcesDirectory)\num_of_version.txt"
          $Version = "1.0.0.$X"
          $newValue = [int]$X + 1
          $newValueAsString = $newValue.ToString()

          Set-Content -Path "$(Build.SourcesDirectory)\num_of_version.txt" -value $newValueAsString
        displayName: 'Update num_of_version.txt'
        
      - task: PowerShell@2
        inputs:
          filePath: 'ADO_custom_build_task.ps1'
          arguments: '"Student Task", "Ilai Gam Zu Letova", "Sort App"'

      - task: DotNetCoreCLI@2
        inputs:
          command: 'run'
          projects: 'sort_list.csproj'

      - powershell: |
          $newValue = Get-Content -Path "$(Build.SourcesDirectory)\num_of_version.txt" | Foreach-Object { [int]$_ + 1 }
          $newValueAsString = $newValue.ToString()
          echo $newValueAsString
          Set-Content -Path "$(Build.SourcesDirectory)\num_of_version.txt" -Value $newValueAsString
        displayName: 'Update num_of_version.txt'
        
      - powershell: |
          Copy-Item -Path "$(Build.SourcesDirectory)/file_sol.txt" -Destination "$(Build.ArtifactStagingDirectory)" -Force
          Copy-Item -Path "$(Build.SourcesDirectory)/num_of_version.txt" -Destination "$(Build.SourcesDirectory)/num_of_version_updated.txt" -Force
        displayName: 'Copy files'


      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'Sort list'
