---

trigger:
  - master
jobs:
  - job: run_custom_task
    pool:   
      vmImage: ubuntu-latest
    variables:
      buildConfiguration: Build
    steps:
      - powershell: >
          
          $env:FILE_1_PATH = "$(Build.SourcesDirectory)\file_1.txt"

          $env:FILE_2_PATH = "$(Build.SourcesDirectory)\file_2.txt"

          $env:OUTPUT_FILE_PATH = "$(Build.SourcesDirectory)\file_sol.txt"
          
          $env:X = "$(Build.SourcesDirectory)\num_of_version.txt"
          
          $Version = "1.0.0.$X"
          # Convert the current value to an integer, increment it, and convert it back to a string
          $newValue = [int]$currentValue + 1
          $newValueAsString = $newValue.ToString()

          # Update the file with the new value
          $newValueAsString | Set-Content -Path "$(Build.SourcesDirectory)\num_of_version.txt"
          #$newVersion | Set-Content "$(Build.SourcesDirectory)\num_of_version.txt"
      - task: Assembly-Info-NetCore@3
        inputs:
          Path: '$(Build.SourcesDirectory)'
          FileNames: '**/*.csproj'
          InsertAttributes: true
          FileEncoding: 'auto'
          WriteBOM: false
          Company: 'Ilai Gam Zu Letova'
          Product: 'Sort App'
          Description: 'Student task'
          VersionNumber: '$(Version)'  
          FileVersionNumber: '$(Version)' 
          LogLevel: 'verbose'
          FailOnWarning: false
          DisableTelemetry: false

      - task: PowerShell@2
        inputs:
          filePath: 'custom_1.ps1'
          arguments: '"Student Task", "Ilai Gam Zu Letova", "Sort App"'
      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'
          projects: 'sort_list.csproj'
      - task: CopyFiles@2
        inputs:
          sourceFolder: '$(Build.SourcesDirectory)/file_sol.txt'
          targetFolder: '$(Build.ArtifactStagingDirectory)'
      - script: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add $(Build.SourcesDirectory)/file_sol.txt
          git commit -m "Updating version and other attributes"
          git commit -m "Update file num_of_version"
          git add $(Build.SourcesDirectory)\num_of_version.txt
          git push -m 
          
          displayName: 'Commit and Push Changes'
          condition: succeeded()






      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'Sort list'

     