---

trigger:
  - master
jobs:
  - job: run_custom_task
    pool:
      vmImage: ubuntu-latest
    variables:
      buildConfiguration: Build
    steps:
      - powershell: >
          
          $env:FILE_1_PATH = "$(Build.SourcesDirectory)\path\to\file_1.txt"

          $env:FILE_2_PATH = "$(Build.SourcesDirectory)\path\to\file_2.txt"

          $env:OUTPUT_FILE_PATH = "$(Build.SourcesDirectory)\path\to\file_sol.txt"

      - task: Assembly-Info-NetCore@3
        inputs:
          Path: '$(Build.SourcesDirectory)'
          FileNames: '**/*.csproj'
          InsertAttributes: true
          FileEncoding: 'auto'
          WriteBOM: false
          Company: 'Ilai Gam Zu Letova'
          Product: 'Sort App'
          Description: 'Student task'
          VersionNumber: '1.0.0.0' 
          FileVersionNumber: '1.0.0.0'
          LogLevel: 'verbose'
          FailOnWarning: false
          DisableTelemetry: false
      - task: PowerShell@2
        inputs:
          filePath: custom_1.ps1
          arguments: '"Student Task", "Ilai Gam Zu Letova", "Sort App"'
      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'
          projects: 'sort_list.csproj'
      - task: CopyFiles@2
        inputs:
          sourceFolder: '$(Build.SourcesDirectory)/file_sol.txt'
          targetFolder: '$(Build.ArtifactStagingDirectory)'
      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: '$(Build.ArtifactStagingDirectory)'
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'Sort list'
          publishLocation: 'Container'