---
trigger:
  - master
jobs:
  - job: run_custom_task
    pool:
      vmImage: ubuntu-latest
    variables:
      buildConfiguration: Build
    steps:
      - powershell: >
          
          $env:FILE_1_PATH = "$(Build.SourcesDirectory)\path\to\file_1.txt"

          $env:FILE_2_PATH = "$(Build.SourcesDirectory)\path\to\file_2.txt"

          $env:OUTPUT_FILE_PATH = "$(Build.SourcesDirectory)\path\to\file_sol.txt"

      - task: Assembly-Info-NetCore@3
        inputs:
          Path: '$(Build.SourcesDirectory)'
          FileNames: 'Assembly_info.csproj'
          InsertAttributes: false
          FileEncoding: 'auto'
          WriteBOM: false
          LogLevel: 'verbose'
          FailOnWarning: false
          DisableTelemetry: false
          # Run the PowerShell script dotnet run
      - task: PowerShell@2
        inputs:
          filePath: custom_1.ps1
          arguments: '"Student Task", "Ilai Gam Zu Letova", "Sort App"'
