# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

jobs:
- job: run_custom_task
  pool:
    vmImage: ubuntu-latest

  variables:
    buildConfiguration: 'Build'

  steps:
  - checkout: self
  - script: dotnet build sort_list.csproj --configuration $(buildConfiguration) #'**/*.csproj' --configuration $(buildConfiguration)
    displayName: 'Run sorted list build'

  - powershell: |
      param(
        [string]$ValueFromPipeline_1 = "Student Task",
        [string]$ValueFromPipeline_2 = "ilai",
        [string]$ValueFromPipeline_3 = "Sort App"
      )

      $env:FILE_1_PATH = "$(Build.SourcesDirectory)\path\to\file_1.txt"
      $env:FILE_2_PATH = "$(Build.SourcesDirectory)\path\to\file_2.txt"
      $env:OUTPUT_FILE_PATH = "$(Build.SourcesDirectory)\path\to\file_sol.txt"

      # Run your .NET program or any other tasks
      dotnet run

      # Run the PowerShell script
      .\custom_1.ps1 -ValueFromPipeline_1 $ValueFromPipeline_1 -ValueFromPipeline_2 $ValueFromPipeline_2 -ValueFromPipeline_3 $ValueFromPipeline_3
    displayName: 'Run PowerShell script'
