---

trigger:
  - master
jobs:
  - job: run_custom_task
    pool:   
      vmImage: ubuntu-latest
    variables:
      buildConfiguration: Build
    steps:
      - powershell: >
          
          $env:FILE_1_PATH = "$(Build.SourcesDirectory)\path\to\file_1.txt"

          $env:FILE_2_PATH = "$(Build.SourcesDirectory)\path\to\file_2.txt"

          $env:OUTPUT_FILE_PATH = "$(Build.SourcesDirectory)\path\to\file_sol.txt"

      - task: Assembly-Info-NetCore@3
        inputs:
          Path: '$(Build.SourcesDirectory)'
          FileNames: '**/AssemblyInfo.cs'
          InsertAttributes: true
      - task: PowerShell@2
        inputs:
          filePath: 'custom.ps1'
          arguments: '"Student Task", "Ilai Gam Zu Letova", "Sort App"'
      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'
          projects: 'sort_list.csproj'
      - task: CopyFiles@2
        inputs:
          sourceFolder: '$(Build.SourcesDirectory)/file_sol.txt'
          targetFolder: '$(Build.ArtifactStagingDirectory)'
      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'Sort list'

     