trigger:
  - master

jobs:
  - job: run_custom_task
    pool:
      vmImage: ubuntu-latest
    variables:
      buildConfiguration: Build
    steps:
      - powershell: |
          $env:ValueFromPipeline_1 = "Student Task"
          $env:ValueFromPipeline_2 = "Ilai Gam Zu Letova"
          $env:ValueFromPipeline_3 = "Sort App"
      - task: Assembly-Info-NetCore@3
        inputs:
          Path: '$(Build.SourcesDirectory)'
          FileNames: '**/AssemblyInfo.*.cs'
          InsertAttributes: true
          FileEncoding: 'auto'
          WriteBOM: false
          Company: $(ValueFromPipeline_2)
          Product: $(ValueFromPipeline_3)
          Description: $(ValueFromPipeline_1)
          VersionNumber: '1.0.0.0'
          FileVersionNumber: '1.0.0.0'
          LogLevel: 'verbose'
          FailOnWarning: false
          DisableTelemetry: false
      - task: PowerShell@2
        inputs:
          filePath: custom_1.ps1
      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'
          projects: '**/*.csproj'
