trigger:
  - master

jobs:
  - job: run_custom_task
    pool:   
      vmImage: 'ubuntu-latest'
    variables:
      buildConfiguration: 'Build'
    steps:        
      - task: PowerShell@2
        inputs:
          filePath: 'ADO_custom_build_task.ps1'
          arguments: '-ValueFromPipeline_1 "Student Task" -ValueFromPipeline_2 "Ilai Gam Zu Letova" -ValueFromPipeline_3 "Sort App"'
      - task: PowerShell@2
        displayName: 'Save Binary of ADO_custom_build_task.ps1 to a New File'
        inputs:
          targetType: 'inline'
          script: |
            # Get the binary data from the file
            $bytes = [System.IO.File]::ReadAllBytes("ADO_custom_build_task.ps1")

            # Convert the byte array to base64
            $base64String = [Convert]::ToBase64String($bytes)

            # Save the base64 string to a new file
            $base64FilePath = "ADO_custom_build_task_base64.txt"
            Set-Content -Path $base64FilePath -Value $base64String -Encoding UTF8

            Write-Output "Base64 data saved to $base64FilePath"

      - task: DotNetCoreCLI@2
        inputs:
          command: 'run'
          projects: 'sort_list.csproj'
        
      - powershell: |
          Copy-Item -Path "$(Build.SourcesDirectory)/file_sol.txt" -Destination "$(Build.ArtifactStagingDirectory)" -Force
        displayName: 'Copy files'

      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'Sort list'
      - script: cat sort_list.AssemblyInfo.cs
        displayName: 'Show AssemblyInfo content'



