- powershell: |
    param(
        [string]$ValueFromPipeline_1 = "tudent Task",
        [string]$ValueFromPipeline_2 = "ilai",
        [string]$ValueFromPipeline_3 = "Sort App"
    )
    
    jobs:
- job: Build
  steps:
  - powershell: |
      $env:FILE_1_PATH = "$(Build.SourcesDirectory)\path\to\file_1.txt"
      $env:FILE_2_PATH = "$(Build.SourcesDirectory)\path\to\file_2.txt"
      $env:OUTPUT_FILE_PATH = "$(Build.SourcesDirectory)\path\to\file_sol.txt"

      dotnet run

    .\ https://dev.azure.com/ilaigamzu13/Devops_student_task/_git/DevOps_task3?path=/project_2/custom_1.ps1&version=GBmaster -ValueFromPipeline_1 $ValueFromPipeline_1 -ValueFromPipeline_2 $ValueFromPipeline_2 -ValueFromPipeline_3 $ValueFromPipeline_3
  displayName: 'Run PowerShell script'
